// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GameSettingsColumns holds the columns for the "game_settings" table.
	GameSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "fire_rate", Type: field.TypeFloat64, Default: 0.08},
		{Name: "bullet_speed", Type: field.TypeFloat64, Default: 22},
		{Name: "level_count", Type: field.TypeInt, Default: 5},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// GameSettingsTable holds the schema information for the "game_settings" table.
	GameSettingsTable = &schema.Table{
		Name:       "game_settings",
		Columns:    GameSettingsColumns,
		PrimaryKey: []*schema.Column{GameSettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gamesettings_id",
				Unique:  true,
				Columns: []*schema.Column{GameSettingsColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GameSettingsTable,
	}
)

func init() {
}
