// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"doomlike/ent/gamesettings"
	"doomlike/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameSettingsDelete is the builder for deleting a GameSettings entity.
type GameSettingsDelete struct {
	config
	hooks    []Hook
	mutation *GameSettingsMutation
}

// Where appends a list predicates to the GameSettingsDelete builder.
func (_d *GameSettingsDelete) Where(ps ...predicate.GameSettings) *GameSettingsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GameSettingsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GameSettingsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GameSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gamesettings.Table, sqlgraph.NewFieldSpec(gamesettings.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GameSettingsDeleteOne is the builder for deleting a single GameSettings entity.
type GameSettingsDeleteOne struct {
	_d *GameSettingsDelete
}

// Where appends a list predicates to the GameSettingsDelete builder.
func (_d *GameSettingsDeleteOne) Where(ps ...predicate.GameSettings) *GameSettingsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GameSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gamesettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GameSettingsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
