// Code generated by ent, DO NOT EDIT.

package ent

import (
	"doomlike/ent/gamesettings"
	"doomlike/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gamesettingsFields := schema.GameSettings{}.Fields()
	_ = gamesettingsFields
	// gamesettingsDescFireRate is the schema descriptor for fire_rate field.
	gamesettingsDescFireRate := gamesettingsFields[1].Descriptor()
	// gamesettings.DefaultFireRate holds the default value on creation for the fire_rate field.
	gamesettings.DefaultFireRate = gamesettingsDescFireRate.Default.(float64)
	// gamesettingsDescBulletSpeed is the schema descriptor for bullet_speed field.
	gamesettingsDescBulletSpeed := gamesettingsFields[2].Descriptor()
	// gamesettings.DefaultBulletSpeed holds the default value on creation for the bullet_speed field.
	gamesettings.DefaultBulletSpeed = gamesettingsDescBulletSpeed.Default.(float64)
	// gamesettingsDescLevelCount is the schema descriptor for level_count field.
	gamesettingsDescLevelCount := gamesettingsFields[3].Descriptor()
	// gamesettings.DefaultLevelCount holds the default value on creation for the level_count field.
	gamesettings.DefaultLevelCount = gamesettingsDescLevelCount.Default.(int)
	// gamesettingsDescID is the schema descriptor for id field.
	gamesettingsDescID := gamesettingsFields[0].Descriptor()
	// gamesettings.DefaultID holds the default value on creation for the id field.
	gamesettings.DefaultID = gamesettingsDescID.Default.(string)
}
