// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GameSettings is the predicate function for gamesettings builders.
type GameSettings func(*sql.Selector)
